### ISSUE TITLE
Loading AMD module with webpack

### ISSUE THREAD

**Issue by dominik01** [rikschennink/conditioner#101]
Hi, I am migrating project from requireJs to Webpack and I have some difficulties with loading modules with conditioner. I spent many hours googling but no success, I would be grateful if someone could help me.

I am loading data-module social-profiles from my index.html file and I am getting error
`Error: Cannot find module '/src/ui/social-profiles.js'`
I checked webpack and amd boilerplates, double checked routes and I am still getting error, don't know why.

I created only simple project where I simulated the issue. Index.js is the entry point for webpack. Here I load my custom library conditional-loader.js which require conditioner and call hydrate. After that I get the error about social-profiles module which is written in AMD.
Link to github sample:
https://github.com/dominik01/webpacksample

Thanks

**Comment by rikschennink** [comment]
Hi,

There's a lot going on in that sample project. I would start with making it more basic. What I do see is that both the old and the new Conditioner library are included. I would also inspect the dist files to see if the modules has been given the correct id.
