### ISSUE TITLE
How to get exported value from module?

### ISSUE THREAD

**Issue by tanangular** [rikschennink/conditioner#104]
<img width="1415" alt="Screenshot 2562-09-18 at 22 54 22" src="https://user-images.githubusercontent.com/1311673/65173563-41b83500-da79-11e9-82b8-2b1fe1ba08ec.png">

in document "moduleGetDestructor" : Gets the destructor method from the module constructor return value, by default expects a single function.
May be moduleGetDestructor is the right choice? or Is there anyway to get exported value from module?

Thanks in advance.

**Comment by rikschennink** [comment]
I'm not sure I understand the question, can you elaborate?

**Comment by rikschennink** [comment]
closed because inactive for 8 days
