### ISSUE TITLE
No AMD loader dependecy

### ISSUE THREAD

**Issue by rikschennink** [rikschennink/conditioner#81]
Look into possibility of detaching entire load mechanism.

**Comment by branneman** [comment]
+1!

So that for example [ES6 Module Loader Polyfill](https://github.com/ModuleLoader/es6-module-loader) could also be used.

**Comment by joeshub** [comment]
+1

**Comment by rikschennink** [comment]
I will look into this further. 

Do note that you can override the default loader (RequireJS) as shown here for WebPack:
https://github.com/rikschennink/conditioner-boilerplate-webpack/blob/master/src/js/main.js

**Comment by rikschennink** [comment]
Resolved with version Conditioner 2.
