### ISSUE TITLE
.sync() doesn't publish a load event when all modules that are available are also loaded 

### ISSUE THREAD

**Issue by mark-ettema** [rikschennink/conditioner#83]
Situation:
A module is attached to a node and has a condition. (eg. `"conditions": "media:{(min-width:400em)}"`) If I supply the module controller to .sync() and the condition is not met, the SyncedControllerGroep will still wait for a load event for this module.

I expext that the SyncedControllerGroup will filter these module controllers (like filter logic below) so it will publish a load event when all modules that are available are loaded.

```javascript
/**
 * @param   {ModuleController}  module
 * @returns {Boolean}
 */
p.isGoingToBeLoaded = function (module) {
    return !module.isModuleActive() && module.isModuleAvailable();
};
```

**Comment by rikschennink** [comment]
The `sync` method is there to synchronize the load events on the passed module or node controllers. So if there's a inactive controller in the list it should not throw a load event as not all controllers have loaded.

I guess you're currently using the sync method to bundle load events of underlying modules?

**Comment by mark-ettema** [comment]
I want to know if all modules are loaded which met current conditions. For instance all modules in a HTML node on desktop. If a module in this HTML node is configured to only load on mobile, the sync() method will not fire a load event. That means that I need to filter de module controllers before passing them to .sync().

For what situation is the behaviour of .sync() ment?

**Comment by rikschennink** [comment]
Suppose you want to setup communication between to modules but you only want that to happen if both modules are loaded. That's when you can use the `sync` method. So you receive one load event and one unload event to start and stop communication.

Are you looking for a way to query conditioner for the current modules within a context that are loaded?
