### ISSUE TITLE
Add version number in minified version

### ISSUE THREAD

**Issue by awolkers** [rikschennink/conditioner#87]
At this moment it's not possible to see what version of conditioner I am using because there is no comments within the script which notices this.

**Comment by rikschennink** [comment]
Excellent point, should be in there, probably some issue with the build script. WIll fix asap.

**Comment by rikschennink** [comment]
Quick fix on master branch and bower. Next release will contain fixed gulp script.

**Comment by awolkers** [comment]
Great!
