### ISSUE TITLE
bower version is 1.2.0 instead of 1.2.2

### ISSUE THREAD

**Issue by aufdenpunkt** [rikschennink/conditioner#96]
Hi, as mentioned bower installs version 1.2.0 instead of 1.2.2.

**Comment by rikschennink** [comment]
Hey! I had some trouble uploading to NPM so had to up the version number, the Bower version is identical to 1.2.2 (a bit confusing..)

I'll see if I can sort it out in the near future.

**Comment by rikschennink** [comment]
Versions are now all at 1.2.3
